version: '3.7'

services:
  db:
    ports:
      - "5435:5432"

  redis:
    build:
      context: docker
      dockerfile: Redis.Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  pgdata:
