services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5414:5432"
    networks:
        - secrets_net

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      target: local
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8014:8000"
    volumes:
      - "./backend:/opt/app/backend"
    networks:
      - secrets_net

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      target: local
    env_file:
      - .env
    ports:
      - "3014:3000"
    restart: unless-stopped
    volumes:
      - "./frontend:/opt/app/frontend"
    networks:
      - secrets_net

volumes:
  pg_data:
networks:
  secrets_net:
    name: secrets_net
