services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5414:5432"
    networks:
        - secrets_net

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
      target: dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8014:8000"
    depends_on:
      - db
    volumes:
      - "./app:/opt/app/app"
    networks:
      - secrets_net
volumes:
  pg_data:
networks:
  secrets_net:
    name: secrets_net
