name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: secrets_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.2
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 src
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pip install pytest
        pytest -s -v
